stages:
  - lint
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby

.before_script_template: &build
  before_script:
    - gem install bundler
    - bundle install

rubocop:
  image: ruby:2.6.2
  <<: *build
  script:
    - bundle exec rubocop
  stage: lint

rspec:
  image: ruby:2.6.2
  <<: *build
  script:
    - bundle exec rubocop
  stage: test

deploy:
  image: ruby:2.6.2
  <<: *build
  script:
    # install dpl:
    - apt-get update -qy
    - apt-get install rubygems ruby-dev -y
    - gem install dpl
    # deploy to heroku:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY --skip_cleanup
  stage: deploy
