stages:
  - lint
  - test

.before_script_template: &build_test-integration
  before_script:
    - gem install bundler
    - bundle install

rubocop:
  image: ruby:2.6
  <<: *build_test-integration
  script:
    - bundle exec rubocop
  stage: lint

rspec:
  image: ruby:2.6
  <<: *build_test-integration
  script:
    - bundle exec rubocop
  stage: test