stages:
  - lint
  - test

.before_script_template: &build_test-integration
  before_script:
    # ssh setup
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - gem install bundler
    - bundle install

rubocop:
  image: ruby:2.6.2-alpine
  <<: *build_test-integration
  script:
    - bundle exec rubocop
  stage: lint

rspec:
  image: ruby:2.6.2-alpine
  <<: *build_test-integration
  script:
    - bundle exec rubocop
  stage: test